spring.application.name=vk-bot

logging.level.org.springframework.web.servlet=DEBUG
logging.level.org.springframework.web.client.RestTemplate=DEBUG

vkbot.group.id=236159015
vkbot.confirmation-code=e9be0171
