spring.application.name=vk-bot

logging.level.org.springframework.web.servlet=DEBUG
logging.level.org.springframework.web.client.RestTemplate=DEBUG
logging.level.com.studlgu.vkbot=INFO


vkbot.group-id=236159015
vkbot.confirmation-code=2dd02b46
vkbot.access-token=vk1.a.coMBvupSO2OqKCOFxLvx1f25wYnCBa_83tOmdfm50y8Ir8UqnxmxOlN8ryJsb-e0Var0SY0_lG6s0wZdAdlkrVOJPFa3-IzZ3SquuT3-AHxWr3rsDSY8O1vvtVulscpJE8x4gtJRZ-727Xrnh69ZIoxt1S5XwmYC6-R_UwqFADuu4jdemWqtmfodXB5kHk-YqaNlRlJj3-SUC_ZXxDrxMw

# ??????? ? ?????? ??? ?????????? ??????? ??? ?????? ??????
vkbot.week-start-date=2025-09-01

#
vkbot.editor-roles=administrator;moderator;editor;creator
