spring.application.name=vk-bot

logging.pattern.dateformat=yyyy-MM-dd HH:mm:ss.SSS,Europe/Moscow
logging.level.org.springframework.web.servlet=DEBUG
logging.level.org.springframework.web.client.RestTemplate=DEBUG
logging.level.com.studlgu.vkbot=INFO

vkbot.group-id=${VKBOT_GROUP_ID}
vkbot.confirmation-code=${VKBOT_CONFIRMATION_CODE}
vkbot.access-token=${VKBOT_ACCESS_TOKEN}

# ??????? ? ?????? ??? ?????????? ??????? ??? ?????? ??????
vkbot.week-start-date=${VKBOT_WEEK_START_DATE}

#
vkbot.editor-roles=${VKBOT_EDITOR_ROLES}

#
vkbot.photo.storage.path=${VKBOT_PHOTO_STORAGE_PATH}
vkbot.events.storage.path=${VKBOT_EVENTS_STORAGE_PATH}
vkbot.appeals.storage.path=${VKBOT_APPEALS_STORAGE_PATH}
